version: 2.1
jobs:
    Devopp:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
    Devopp1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
    Devopp2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
    Devopp3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
workflows:
    version: 2.1
    build:
        jobs:
            - Devopp
            - Devopp1
            - Devopp2
            - Devopp3